//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapFramework.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ConfigApplication : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigApplication defaultInstance = ((ConfigApplication)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigApplication())));
        
        public static ConfigApplication Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAPApplication")]
        public string SAPApplication {
            get {
                return ((string)(this["SAPApplication"]));
            }
            set {
                this["SAPApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAPCompany")]
        public string SAPCompany {
            get {
                return ((string)(this["SAPCompany"]));
            }
            set {
                this["SAPCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("log")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
            set {
                this["LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AddOnLog")]
        public string LogName {
            get {
                return ((string)(this["LogName"]));
            }
            set {
                this["LogName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConnString")]
        public string SAPConnectionString {
            get {
                return ((string)(this["SAPConnectionString"]));
            }
            set {
                this["SAPConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000")]
        public int SAPConnectionControlInterval {
            get {
                return ((int)(this["SAPConnectionControlInterval"]));
            }
            set {
                this["SAPConnectionControlInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateReports {
            get {
                return ((bool)(this["CreateReports"]));
            }
            set {
                this["CreateReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LastSortedCol")]
        public string LastSortedCol {
            get {
                return ((string)(this["LastSortedCol"]));
            }
            set {
                this["LastSortedCol"] = value;
            }
        }
    }
}
